### PR TITLE
Symlink CloudBuildSource.

### PR DESCRIPTION
**Pull request by Harwayne**
## Proposed Changes

- Symlink `config/300-cloudbuildsource.yaml`.

### CODE REVIEW

**Comment by yolocs** [comment]
Integ test shows error `2020/04/16 02:58:55 error processing import paths in "config/300-cloudbuildsource.yaml": open config/300-cloudbuildsource.yaml: no such file or directory`

**Comment by Harwayne** [comment]
> Integ test shows error `2020/04/16 02:58:55 error processing import paths in "config/300-cloudbuildsource.yaml": open config/300-cloudbuildsource.yaml: no such file or directory`

I had an extra leading `config/` in the link originally. Removed.

**Pull request merged**
