### PR TITLE
Re-org config files

### PR DESCRIPTION
**Pull request by nachocano**
Fixes https://github.com/google/knative-gcp/issues/585

## Proposed Changes

- Internal reorg of config files to match eventing and serving.
- This will help with the workload identity work.

```release-note
NONE
```

### CODE REVIEW

**Comment by grac3gao** [comment]
It seems `config/201-clusterrole.yaml` doesn't have symlink?

**Comment by nachocano** [comment]
> It seems `config/201-clusterrole.yaml` doesn't have symlink?

oops let me fix that

**Comment by nachocano** [comment]
@grac3gao done!

**Comment by nachocano** [comment]
flaky

/test pull-google-knative-gcp-integration-tests

**Pull request merged**
