### PR TITLE
Use the PublishSettings, rather than always using DefaultPublishSetti…

### PR DESCRIPTION
**Pull request by Harwayne**
## Proposed Changes

- 🐛 Use the PublishSettings, rather than always using `DefaultPublishSettings`.

**Release Note**

```release-note
NONE
```

### CODE REVIEW

**Comment by tayarani** [comment]
Is this testable? Like adding a simple unit test or e2e test?

**Comment by Harwayne** [comment]
> Is this testable? Like adding a simple unit test or e2e test?

Added a unit test.

**Comment by tayarani** [comment]
Thanks for adding the test.

/lgtm

**Comment by Harwayne** [comment]
> @Harwayne: The following test **failed**, say `/retest` to rerun all failed tests:
> 
> Test name	Commit	Details	Rerun command
> pull-google-knative-gcp-upgrade-tests	[b82a91b](https://github.com/google/knative-gcp/commit/b82a91bb509808483c0581312a97937bd1ec8768)	[link](https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/google_knative-gcp/2093/pull-google-knative-gcp-upgrade-tests/1353799028210405376)	`/test pull-google-knative-gcp-upgrade-tests`
> [Full PR test history](https://gubernator.knative.dev/pr/google_knative-gcp/2093). [Your PR dashboard](https://gubernator.knative.dev/pr/Harwayne).

```
Error from server (InternalError): error when creating "https://storage.googleapis.com/knative-nightly/net-istio/latest/net-istio.yaml": Internal error occurred: failed calling webhook "config.webhook.serving.knative.dev": Post https://webhook.knative-serving.svc:443/config-validation?timeout=10s: no endpoints available for service "webhook"
```

/retest

**Pull request merged**
