### PR TITLE
Use errgroup to wait for goroutines in adapter tests

### LINKED ISSUE #1374: Data race detected for TestAdapter/successful_with_no_reply
**Describe the bug**
See
https://prow.knative.dev/view/gcs/knative-prow/pr-logs/pull/google_knative-gcp/1356/pull-google-knative-gcp-unit-tests/1278405653475364864

This is the first time I see it. Doesn't seem to happen often.

### PR DESCRIPTION
**Pull request by ian-mi**
Fixes #1374

### CODE REVIEW

**Comment by nachocano** [comment]
/retest
/lgtm
/approve

Thanks for fixing this @ian-mi !!!

**Comment by ian-mi** [comment]
Thanks! Should be ready to merge now.

**Pull request merged**
