### PR TITLE
Provide the default GCP auth during the creation of the PullSubscription for E2E

### PR DESCRIPTION
**Pull request by Harwayne**
## Proposed Changes

- Provide the default GCP auth during the creation of the PullSubscription for E2E
  - This doesn't alter the outcome of the tests, but before this change an error log was generated stating `Failed to get the GCPAuthDefaults`.

**Release Note**

```release-note
NONE
```

### CODE REVIEW

**Comment by capri-xiyue** [comment]
Can you also change similar things for other resources under https://github.com/google/knative-gcp/tree/master/pkg/reconciler/testing like https://github.com/google/knative-gcp/blob/b84068ef56418037d46819c1266ce9f9e3d55911/pkg/reconciler/testing/storage.go#L53?

**Comment by Harwayne** [comment]
> Can you also help change similar things for other resources under https://github.com/google/knative-gcp/tree/master/pkg/reconciler/testing like
> 
> https://github.com/google/knative-gcp/blob/b84068ef56418037d46819c1266ce9f9e3d55911/pkg/reconciler/testing/storage.go#L53
> 
> ?

Done.

At least the ones I noticed.

**Pull request merged**
