### PR TITLE
Update docs for CloudBuildSource to use v1

### LINKED ISSUE #1413: Promote CloudBuildSource to v1
**Problem**
We need to promote CloudBuildSource to v1.
Some tasks this will entail, and can probably be done in different PRs.

- [x] v1 types with UTs
- [x] add new version to CRD
- [x] defaulting and conversion webhook
- [ ] Update docs and examples
- [ ] Migrate reconciler to v1 with UTs
- [ ] Add e2e tests to also support v1

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Developer

**Exit Criteria**
Build source is in v1

### PR DESCRIPTION
**Pull request by danyinggu**
Fixes #1413 

## Proposed Changes

- Update docs for CloudBuildSource to use v1
-
-

**Release Note**

```release-note

```

**Docs**

### CODE REVIEW

**Comment by capri-xiyue** [comment]
@danyinggu  Have you run the https://github.com/google/knative-gcp/blob/master/docs/examples/cloudbuildsource/README.md to see whether the CloudBuildSource still works?

**Comment by danyinggu** [comment]
> @danyinggu Have you run the https://github.com/google/knative-gcp/blob/master/docs/examples/cloudbuildsource/README.md to see whether the CloudBuildSource still works?

Yes. I have run the examples and it is still working.

```☁️  cloudevents.Event
Validation: valid
Context Attributes,
  specversion: 1.0
  type: google.cloud.cloudbuild.build.v1.statusChanged
  source: //cloudbuild.googleapis.com/projects/danyinggu-knative-dev/builds/f36e2eab-66f7-47d1-b2b0-8f6a0023f6d4
  subject: SUCCESS
  id: 1489764232607150
  time: 2020-09-02T17:05:25.619Z
  dataschema: https://raw.githubusercontent.com/googleapis/google-cloudevents/master/proto/google/events/cloud/cloudbuild/v1/data.proto
  datacontenttype: application/json
Data,
  {
    "name": "projects/2935505130/locations/global/builds/f36e2eab-66f7-47d1-b2b0-8f6a0023f6d4",
    "id": "f36e2eab-66f7-47d1-b2b0-8f6a0023f6d4",
    "projectId": "danyinggu-knative-dev",
    "status": "SUCCESS",
    "source": {
      "storageSource": {
        "bucket": "danyinggu-knative-dev_cloudbuild",
        "object": "source/1599066310.154268-4116e8dcc6e94e1a9932c1dd27442a80.tgz",
        "generation": "1599066310786834"
      }
    },
    "steps": [
      {
        "name": "gcr.io/cloud-builders/docker",
        "args": [
          "build",
          "--network",
          "cloudbuild",
          "--no-cache",
          "-t",
          "gcr.io/danyinggu-knative-dev/quickstart-image",
          "."
        ],
        "timing": {
          "startTime": "2020-09-02T17:05:18.625862587Z",
          "endTime": "2020-09-02T17:05:20.189610540Z"
        },
        "pullTiming": {
          "startTime": "2020-09-02T17:05:18.625862587Z",
          "endTime": "2020-09-02T17:05:18.631763807Z"
        },
        "status": "SUCCESS"
      }
    ],
```
and 

```
 kubectl describe sources
Name:         cloudbuildsource-test
Namespace:    default
Labels:       <none>
Annotations:  cluster-name: cluster-1
API Version:  events.cloud.google.com/v1
Kind:         CloudBuildSource
Metadata:
  Creation Timestamp:  2020-09-02T17:03:17Z
  Finalizers:
    cloudbuildsources.events.cloud.google.com
  Generation:        1
  Resource Version:  136814027
  Self Link:         /apis/events.cloud.google.com/v1/namespaces/default/cloudbuildsources/cloudbuildsource-test
  UID:               4c82e7c3-9c0b-4a4e-8490-39266189afc3
Spec:
  Secret:
    Key:   key.json
    Name:  google-cloud-key
  Sink:
    Ref:
      API Version:  v1
      Kind:         Service
      Name:         event-display
Status:
  Conditions:
    Last Transition Time:  2020-09-02T17:03:22Z
    Status:                True
    Type:                  PullSubscriptionReady
    Last Transition Time:  2020-09-02T17:03:22Z
    Status:                True
    Type:                  Ready
  Observed Generation:     1
  Sink Uri:                http://event-display.default.svc.cluster.local/
  Subscription Id:         cre-src_default_cloudbuildsource-test_e128898e-9065-43f9-942d-d4ca40469fad
```

**Pull request merged**
