### PR TITLE
Add resync period to brokercell controller

### PR DESCRIPTION
**Pull request by liu-cong**
Fixes #

## Proposed Changes

-
-
-

**Release Note**

```release-note

```

**Docs**

### CODE REVIEW

**Comment by capri-xiyue** [comment]
The code looks good to me. I think I missed some context. Just curious why do we need resync here? Is there any change outside of the cluster that we need to periodically check?

**Comment by liu-cong** [comment]
> The code looks good to me. I think I missed some context. Just curious why do we need resync here? Is there any change outside of the cluster that we need to periodically check?

It's just a general practice to make the system more resilient, in case certain events are lost, or not fully handled. We hope with resync the system will eventually drive the state to the desired.

**Pull request merged**
