### PR TITLE
Updating dependencies

### PR DESCRIPTION
**Pull request by nachocano**
## Proposed Changes

- Updating eventing, pkg, and serving to latest..
- Reverting the `default.webhook.events.cloud.google.com` to `webhook.events.cloud.google.com`, as in 0.10.1 branch (thanks @grantr)
- Removing deprecated fields in SubscribableTypeStatus.
- Removing fake lister as in [#2227](https://github.com/knative/eventing/pull/)

NOTE: we need the sockpuppet here...

**Release Note**

```release-note
NONE
```

### CODE REVIEW

**Comment by nachocano** [comment]
/assign @grantr 
/assign @yolocs 

@yolocs I think this should fix the merge issue.

**Comment by yolocs** [comment]
It seems `TestNew` is failing.

**Comment by nachocano** [comment]
Yeah, there is some new duck typing magic that I still cannot figure out...

**Comment by nachocano** [comment]
@yolocs this should be ready to review...

**Pull request merged**
