### PR TITLE
Refactor setup functions in e2e script

### PR DESCRIPTION
**Pull request by grac3gao**
Fixes #

## Proposed Changes

- Refactor setup functions in e2e script in order to make them shared later.
-
-

**Release Note**

```release-note

```

**Docs**

### CODE REVIEW

**Comment by zhongduo** [comment]
IIUC, you are trying to use `if..else` to merge the same functions in secret mode and WI mode. But I don't see lots of reusable code, in this sense putting those into different function might make sense. You can still have one single entry point with argument to choose which function to invoke. WDYT?

**Comment by grac3gao** [comment]
@zhongduo new functions have other usage, will sync you offline

**Review by danyinggu — COMMENTED** [review]
/lgtm

**Review by danyinggu — COMMENTED** [review]
/lgtm

**Pull request merged**
