### PR TITLE
Revert namespace rename

### PR DESCRIPTION
**Pull request by AlexandraRoatis**
Fixes #

## Proposed Changes

- Rename `events-system-example` from docs to `broker-example`
- Revert namespace rename back to `cloud-run-events`

**Release Note**

```release-note
Revert namespace rename back to `cloud-run-events`.
```

**Docs**

### CODE REVIEW

**Comment by AlexandraRoatis** [comment]
I accidentally used the old master branch. Rebasing now.

**Comment by MohamedElhawaty** [comment]
Should this include removing the `namespace-transition` documentation as well?

**Pull request merged**
