### PR TITLE
Update test-infra to latest

### PR DESCRIPTION
**Pull request by chizhg**
## Proposed Changes
- Serving is going to stop releasing `serving.yaml` in https://github.com/knative/serving/pull/8194, update test-infra to the latest to stop using it.

**Release Note**

```release-note
NONE
```

**Docs**

/assign @nachocano @capri-xiyue

### CODE REVIEW

**Comment by chizhg** [comment]
/hold
It seems there are issues with this approach.

**Comment by chizhg** [comment]
/hold
It seems there are some issues with installing serving in this way.

**Comment by capri-xiyue** [comment]
A lot of reconciler error found in controller logs https://pantheon.corp.google.com/storage/browser/_details/knative-prow/pr-logs/pull/google_knative-gcp/1221/pull-google-knative-gcp-integration-tests/1268695051379150848/artifacts/controller-logs/cloud-run-events-controller-cbd859c6f-27dpp-controller.txt

Similar failures happened in this PR when trying to update the deps in this PR https://github.com/google/knative-gcp/pull/1222

**Comment by nachocano** [comment]
> A lot of reconciler error found in controller logs https://pantheon.corp.google.com/storage/browser/_details/knative-prow/pr-logs/pull/google_knative-gcp/1221/pull-google-knative-gcp-integration-tests/1268695051379150848/artifacts/controller-logs/cloud-run-events-controller-cbd859c6f-27dpp-controller.txt
> 
> Similar failures happened in this PR when trying to update the deps #1222

@chizhg any idea of what can be wrong? The latest serving? I'm trying to update deps as well here: https://github.com/google/knative-gcp/pull/1222, and getting similar errors

**Comment by nachocano** [comment]
I see the same errors @chizhg . And I think is related to serving. They might have changed some conditions or something, because all our tests that use Topic (i.e., a ksvc) are failing. The ones that don't, pass.
I will create a PR to avoid using ksvc in our Sources, because it's unnecessary. But still, the Channel tests will still fail.
Wondering what change they introduced. I'll dig in their PRs later tonight...

**Comment by nachocano** [comment]
Might be something related to this: https://github.com/knative/serving/pull/8137
although for v1 instead of v1beta1...

**Pull request closed without merging**
