### PR TITLE
Address CAL Source e2e test flakiness

### PR DESCRIPTION
**Pull request by nachocano**
## Proposed Changes

- Attempt to reduce flakiness of CALSource E2E test.
- It seems that we are missing an event. Waiting 90 seconds.

**Release Note**

```release-note
NONE
```

### CODE REVIEW

**Comment by nachocano** [comment]
/assign @chizhg 
fyi @capri-xiyue

**Comment by nachocano** [comment]
passed once... trying again

/test pull-google-knative-gcp-integration-tests

**Comment by nachocano** [comment]
passed twice... @chizhg triggered it again to see...

**Comment by nachocano** [comment]
passed third time... 
/test pull-google-knative-gcp-integration-tests

**Comment by chizhg** [comment]
/lgtm
/hold
Please unhold if this passes :)

**Pull request merged**
