### PR TITLE
Issue #1494: Release-0.16 branch vendors an outdated Knative Eventing dependency

### PR DESCRIPTION
**Pull request by Ectelion**
Addresses #1494

### CODE REVIEW

**Comment by nachocano** [comment]
/lgtm
/approve
/hold
until we get the other immutable fix in, so that we don't accidentally trigger two point releases

**Comment by nachocano** [comment]
This is the issue we should cherry-pick to this branch, once we have the fix:
https://github.com/google/knative-gcp/issues/1448

fyi @danyinggu, @bharattkukreja

**Comment by grac3gao** [comment]
Checked the log from the failed WI test, it seems that this branch doesn't use some latest main branch updates to reduce flakiness, like the test sender Pod is still using an old version which doesn't include the retry for certain error code. It might be worthwhile to do a `git merge` to include those updates for reducing the test flakiness if tests kept failing.

**Comment by grac3gao** [comment]
Sorry, I didn't realize it is for release-0.16 branch not for the main branch...then it might experience more flakiness...

**Comment by nachocano** [comment]
Closing this one as we already pushed that change into 0.16 branch

**Pull request closed without merging**
