### PR TITLE
Updating EventTypes

### PR DESCRIPTION
**Pull request by nachocano**
- Updating storage types to `com.google.cloud.storage.object.*`
- Updating pubsub type to `com.google.cloud.pubsub.topic.publish`
- Remove unnecessary local types in storage

### CODE REVIEW

**Comment by nachocano** [comment]
/hold 
until we agree on the exact strings

**Comment by nachocano** [comment]
/assign @vaikas-google 

fyi @aaron-lerner

**Comment by vaikas-google** [comment]
/lgtm
/approve

Those new strings sure are looooong 🤔

**Pull request merged**
