### PR TITLE
Moving to apis.URL, updating deps and fixing compilation issues

### PR DESCRIPTION
**Pull request by nachocano**
## Proposed Changes

- Updating deps, mainly moving to preview7 of sdk.
- Changes to e2e tests due to compilation issues.
- Moving to apis.URL instead of string. This is needed for PullSubscription to implement duckv1.Source. Added the change all over. This is a non-breaking change.

**Release Note**

```release-note
NONE
```

**Docs**

### CODE REVIEW

**Comment by yolocs** [comment]
Some tests seem to be failing?

**Comment by nachocano** [comment]
yeah, it's a mess. Fixing it now, and will ping you in a bit

**Comment by nachocano** [comment]
giving it another try... let's see

**Comment by nachocano** [comment]
not sure why it keeps on asking to update-codegen. I've already done it...

**Comment by nachocano** [comment]
even the integration tests pass.... what is happening here...

/test pull-google-knative-gcp-build-tests

**Pull request merged**
