### PR TITLE
gofmt

### PR DESCRIPTION
**Pull request by ian-mi**

### CODE REVIEW

**Comment by ian-mi** [comment]
@danyinggu Please take another look, another small fix was needed.

**Comment by capri-xiyue** [comment]
Duplicate PRs: https://github.com/google/knative-gcp/pull/1460
Considering the broken CI/CD, we can see which PR gets merged  first and close another PR

**Comment by capri-xiyue** [comment]
/hold
Duplicate PRs: #1460 already got merged

**Pull request closed without merging**
