### PR TITLE
update eventing deps and remove eventing pin

### PR DESCRIPTION
**Pull request by capri-xiyue**
Fixes #

## Proposed Changes

- update eventing deps and remove eventing pin
-
-

### CODE REVIEW

**Comment by capri-xiyue** [comment]
The build failed because of 
`vendor/knative.dev/eventing/test/lib/recordevents/event_info_matchers.go:31:24: undefined: "github.com/cloudevents/sdk-go/v2/test".EventMatcher
vendor/knative.dev/eventing/test/lib/recordevents/event_info_matchers.go:36:11: undefined: "github.com/cloudevents/sdk-go/v2/test".AllOf`
I checked the vendor code, there is no `vendor/knative.dev/eventing/test/lib/recordevents` after we update eventing to latest.
@chizhg Do you have any clue about this?

**Comment by capri-xiyue** [comment]
> The build failed because of
> `vendor/knative.dev/eventing/test/lib/recordevents/event_info_matchers.go:31:24: undefined: "github.com/cloudevents/sdk-go/v2/test".EventMatcher vendor/knative.dev/eventing/test/lib/recordevents/event_info_matchers.go:36:11: undefined: "github.com/cloudevents/sdk-go/v2/test".AllOf`
> I checked the vendor code, there is no `vendor/knative.dev/eventing/test/lib/recordevents` after we update eventing to latest.
> @chizhg Do you have any clue about this?

It looks like we have to update `github.com/cloudevents/sdk-go` at the same time

**Comment by capri-xiyue** [comment]
We failed to update deps because of this https://github.com/google/knative-gcp/blob/a12cfb0e24ef785a5125a0284682d6018c89b0b7/go.mod#L56

**Comment by capri-xiyue** [comment]
@grantr  To remove the eventing nightly pin, we need to update eventing deps.
However, it got blocked because of this  cloudevents sdk pin https://github.com/google/knative-gcp/blob/a12cfb0e24ef785a5125a0284682d6018c89b0b7/go.mod#L56.
And https://github.com/cloudevents/sdk-go/issues/525 is not fixed. Is it ok that we delete this cloudevents sdk pin?

**Comment by grantr** [comment]
Go ahead and try removing it. I think the nature of the original issue was that update-deps would fail without it. If we remove the pin and dependencies end up in the right place and tests pass, I think we're good.

**Comment by capri-xiyue** [comment]
> Go ahead and try removing it. I think the nature of the original issue was that update-deps would fail without it. If we remove the pin and dependencies end up in the right place and tests pass, I think we're good.

It doesn't block uodate-deps. But after we unpin Cloud Events SDK, E2E tests with pubsub channel failed to send cloudvents.

**Comment by capri-xiyue** [comment]
After we update eventing deps and unpin cloudevents sdk,
`TestChannelTracing` passed.
But for 'TestChannelChain` and 
 `TestEventTransformationForSubscription`,
they all fail because of 
`Failed to send event Validation: valid
        Context Attributes,
          specversion: 1.0
          type: dev.knative.test.event
          source: http://e2e-eventtransformation-sender.svc/
          id: dummy
          datacontenttype: application/json
        Data (binary),
          {
            "msg": "TestEventTransformation e52e4eff-2faf-4ae4-8ccd-409065a9bd32"
          }
         with tracing to http://cre-e2e-eventtransformation1-chan-publish.test-event-transformation-for-subscription-channel-messagi84z4h.svc.cluster.local: timed out waiting for the condition`

**Pull request merged**
