### PR TITLE
Channel tracing

### PR DESCRIPTION
**Pull request by Harwayne**
Add tracing to the Channel and thus Topic and PullSubscription. 

There is an E2E test, but it does not pass due to knative/eventing#2046, so it is skipped.

### CODE REVIEW

**Comment by Harwayne** [comment]
I think this is ready for review, PTAL.

**Comment by Harwayne** [comment]
Ping.

**Comment by n3wscott** [comment]
> Ping.

for me, most github messages go into a black hole so dark it is hard to see them...

**Comment by Harwayne** [comment]
@n3wscott merged master and fixed the unit test, PTAL.

**Pull request merged**
