### PR TITLE
[WIP] binded quota to the running project

### PR DESCRIPTION
**Pull request by capri-xiyue**
Fixes #

## Proposed Changes

- binded quota to the running project
-
-

**Release Note**

```release-note

```

**Docs**

### CODE REVIEW

**Comment by capri-xiyue** [comment]
I binded the quota to the running project because of in prow the e2e tests are flaky because of reaching quota limit issues.
Since in prow, all e2e tests of different projects use the same service account which by default the quota will goes to the project which owns the service account.
Not sure whether it will has side effects when we bind quota to the running project.

**Comment by chizhg** [comment]
What's the difference between this and https://github.com/google/knative-gcp/pull/1440? Are they just in different places?

**Comment by capri-xiyue** [comment]
> What's the difference between this and #1440? Are they just in different places?

I checked the error logs.
Now the e2e test failed when we tried to create CloudAuditLogsSource in reconciler which is because when don't bind quota when we create the relevant client. Therefore, I think the quota still goes to the project which owns the service account.

Though I don't know whether we should change the logic in our source code since this e2e test failure issue is kind of related to how we run prow e2e tests.

**Comment by nachocano** [comment]
> > What's the difference between this and #1440? Are they just in different places?
> 
> I checked the error logs.
> Now the e2e test failed when we tried to create CloudAuditLogsSource in reconciler which is because when don't bind quota when we create the relevant client. Therefore, I think the quota still goes to the project which owns the service account.
> 
> Though I don't know whether we should change the logic in our source code since this e2e test failure issue is kind of related to how we run prow e2e tests.

If it's an issue on how we run e2e tests in PROW, I think we shouldn't change the source code.
Do we understand what this binding quota does? Users that run this will get affected with this change?

**Comment by capri-xiyue** [comment]
> > > What's the difference between this and #1440? Are they just in different places?
> > 
> > 
> > I checked the error logs.
> > Now the e2e test failed when we tried to create CloudAuditLogsSource in reconciler which is because when don't bind quota when we create the relevant client. Therefore, I think the quota still goes to the project which owns the service account.
> > Though I don't know whether we should change the logic in our source code since this e2e test failure issue is kind of related to how we run prow e2e tests.
> 
> If it's an issue on how we run e2e tests in PROW, I think we shouldn't change the source code.
> Do we understand what this binding quota does? Users that run this will get affected with this change?

Yep. I agree we should not change the logic in our source code since this e2e test failure issue is kind of related to how we run prow e2e tests.
 Regarding "what this binding quota does", 
`if you're using a service account to do stuff, some operations may count quota against the project that owns the service account rather than the project being operated on, which requires service activation in the service account's project.`
For prow e2e tests, since all e2e tests of different codebase will use the same service account, so all the quotas will go to the gcp project which owns the service account. Therefore, it's more likely to reach quota limits.

User will get  affected with this change if they use a service account which doesn't belong to the running project.
Without quota biding in this PR, the quota will go to the project which owns the service account.
With quota biding in this PR, the quota will go to the running project

**Comment by capri-xiyue** [comment]
@chizhg
Is it possible that knative-gcp has its own service account which belongs to knative-gcp specific prow project so that we don't need to share quota with other teams thttps://github.com/google/knative-gcp/issues/1021

**Comment by capri-xiyue** [comment]
I did some investigation of what other team does. I don't think we should blindly bind the quota to the running project. 
We should allow user to specify the project they want to use for quota and billing.
If they don't specify, we should follow the default behavior of gcp.
New issues created here: https://github.com/google/knative-gcp/issues/1579

**Pull request closed without merging**
