### PR TITLE
Removing deletion/creation/update of resources after 0.16 cut

### PR DESCRIPTION
**Pull request by nachocano**
## Proposed Changes

- 🗑️  Removing the deletion/creation cases needed for a smooth upgrade to 0.16.

**Release Note**

```release-note
NONE
```

**Docs**

### CODE REVIEW

**Comment by Harwayne** [comment]
@googlebot Check

**Comment by nachocano** [comment]
/retest

aaaaaarggggggggggg

**Comment by nachocano** [comment]
/retest
number 20!!! Wohoooo

**Pull request merged**
