### PR TITLE
first cut of storage notification example usage

### PR DESCRIPTION
**Pull request by vaikas-google**

### CODE REVIEW

**Comment by vaikas-google** [comment]
Thanks :) @evankanderson PTAL, I think I got all the comments addressed.

**Comment by vaikas-google** [comment]
Test failed with:
docs/storage/README.md
	ERROR	https://cloud.google/com/console
		Lookup cloud.google on 10.63.240.10:53: server misbehaving


Not quite sure what that's all about 🤔

**Comment by evankanderson** [comment]
> Test failed with:
> docs/storage/README.md
> ERROR	https://cloud.google/com/console
> Lookup cloud.google on 10.63.240.10:53: server misbehaving
> 
> Not quite sure what that's all about 🤔

I'm assuming you figured out that cloud.google is not the DNS name you want. :-D

/lgtm
/approve

**Pull request merged**
