### PR TITLE
Updating deps and moving things to eventing v1beta1

### PR DESCRIPTION
**Pull request by nachocano**
./hack/update-deps.sh --upgrade
Also, v1alpha1 in eventing got completely removed. Changing a few places where we had references to that to start using v1beta1. 
This is blocking upstream changes.

```release-note
NONE
```

**Docs**

### CODE REVIEW

**Comment by nachocano** [comment]
/assign @capri-xiyue 
one more try

**Comment by nachocano** [comment]
fyi @zargarpur this also blocks us for updating upstream

**Comment by capri-xiyue** [comment]
build failed because of `test/e2e/e2e_test.go:51:44: cannot use "github.com/cloudevents/sdk-go".Binary (type untyped string) as type binding.Encoding in argument to "knative.dev/eventing/test/e2e/helpers".SingleEventForChannelTestHelper
test/e2e/e2e_test.go:61:44: cannot use "github.com/cloudevents/sdk-go".Structured (type untyped string) as type binding.Encoding in argument to "knative.dev/eventing/test/e2e/helpers".SingleEventForChannelTestHelper`

**Comment by capri-xiyue** [comment]
A lot of reconciler error found the controller-logs
https://pantheon.corp.google.com/storage/browser/_details/knative-prow/pr-logs/pull/google_knative-gcp/1222/pull-google-knative-gcp-integration-tests/1268694798676529154/artifacts/controller-logs/cloud-run-events-controller-7864c467f6-m6mln-controller.txt

Similar failures happened in this PR when trying to update the deps #1221

**Pull request merged**
