### PR TITLE
Re-enabling channel tests

### PR DESCRIPTION
**Pull request by nachocano**
Fixes https://github.com/google/knative-gcp/issues/486

## Proposed Changes

- attempt to see if these have been fixed already.

**Release Note**

```release-note
NONE
```

### CODE REVIEW

**Comment by nachocano** [comment]
@chizhg BTW, the channel defaulter singleton is gone, so those tests might be fixed as well...
Have you tried enabling them? I can give it a try here as well
https://github.com/knative/eventing-contrib/issues/627

**Comment by chizhg** [comment]
Hmm, seems still flaky?

**Comment by chizhg** [comment]
> @chizhg BTW, the channel defaulter singleton is gone, so those tests might be fixed as well...
> Have you tried enabling them? I can give it a try here as well
> [knative/eventing-contrib#627](https://github.com/knative/eventing-contrib/issues/627)

After this change, does it read the config from the configmap every time we create a new default channel? If not, I think these tests still cannot work..

**Comment by nachocano** [comment]
> Hmm, seems still flaky?

yeah

/test pull-google-knative-gcp-integration-tests

**Comment by nachocano** [comment]
> k these tests still cannot work..

It reads it from a "store" object that is attached to the context. It seems that it doesn't work.. Created a separate one for that...

**Comment by chizhg** [comment]
> > Hmm, seems still flaky?
> 
> yeah
> 
> /test pull-google-knative-gcp-integration-tests

Some of the tests are also flaky when we run them against KafkaChannel, and Ville is trying to find out the root cause in https://github.com/knative/eventing-contrib/pull/920. Is it possible they are the same reason?

**Comment by nachocano** [comment]
> > > Hmm, seems still flaky?
> > 
> > 
> > yeah
> > /test pull-google-knative-gcp-integration-tests
> 
> Some of the tests are also flaky when we run them against KafkaChannel, and Ville is trying to find out the root cause in [knative/eventing-contrib#920](https://github.com/knative/eventing-contrib/pull/920). Is it possible they are the same reason?

hmm not sure, these always fail though, they are not flaky AFAIK... or it seems that the parallelism has something to do?

**Comment by chizhg** [comment]
Seems it does work for `parallel=1` 😮

**Comment by nachocano** [comment]
yes, it's the same thing as kafka then...
the parallel thing just executes other tests in parallel right? although
all should be in different namespaces, right?
there is a concurrency problem somewhere...
Do you know if IMC and Natss work well with 12?

**Comment by chizhg** [comment]
Yes, IMC and Natss works for parallel=12

**Comment by nachocano** [comment]
> Yes, IMC and Natss works for parallel=12 On Mon, Mar 2, 2020, 9:45 PM Ignacio (Nacho) Cano <notifications@github.com> wrote:

hmm, ok there must be some weird stuff that we are doing in kafka and pubsub then. Will try to debug further tomorrow...

**Pull request closed without merging**
