### PR TITLE
Fix prerequisite links in metrics/REAMD.md and install-gcp-broker.md

### LINKED ISSUE #1623: Missing `google-broker-key` secret in `dataplane-service-account.md`
**Describe the bug**
The existing `dataplane-service-account.md` does not create a `google-broker-key` secret, this will result in `Failed to publish to PubSub` error when sending events to the gcp broker. 

 **Expected behavior**
The secret key `google-broker-key` gets created in the documentation.

 **To Reproduce**
With a fresh GKE cluster, follow the instructions in: https://github.com/google/knative-gcp/tree/master/docs/examples/gcpbroker

 **Knative-GCP release version**

 **Additional context**

### PR DESCRIPTION
**Pull request by zhongduo**
Fixes #1623 

## Proposed Changes

- Metrics Example Prerequisites (2) should point to Installing GCP Broker
-  Installing GCP Broker Prerequisites (2) should directly point the specific section https://github.com/google/knative-gcp/blob/master/docs/install/dataplane-service-account.md#create-a-google-cloud-service-account-to-interact-with-pubsub

### CODE REVIEW

**Comment by zhongduo** [comment]
> It seems that in install-gcp-broker.md, link https://knative.dev/docs/eventing/broker/mt-channel-based-broker/ is outdated, so the build test failed.

There is no equivalent in knative.dev any more, should we just remove the link then?

**Comment by grac3gao** [comment]
/retest
/lgtm
/approve

Thanks for fixing it!

**Pull request merged**
