### PR TITLE
Remove static GCP broker data plane  yamls

### LINKED ISSUE #867: BrokerCell creation controller
**Problem**
The first time a Broker is created, we should create a BrokerCell to service it. This can be a separate controller from the normal Broker and BrokerCell controller for simplicity.

If this BrokerCell is modified, the controller shouldn't attempt to reconcile away the differences. If the BrokerCell is deleted, the controller should create a new one.

This controller is optional but recommended since it reduces the footprint of eventing when no eventing objects have been created.

**Time Estimate (optional):** 
2

**Additional context (optional)**
If we later add support for multiple BrokerCells (see #866) this controller should create the BrokerCell a Broker is assigned to if it doesn't exist.

### PR DESCRIPTION
**Pull request by liu-cong**
Fixes #867

## Proposed Changes

- Remove static yamls for GCP broker data plane as now they are created dynamically by brokercell (https://github.com/google/knative-gcp/pull/1132)
- Copy the SA, role and rolebinding in the 200-rbac.yaml to existing rbac files
-

**Release Note**

```release-note
Remove static GCP broker data plane yamls
```

**Docs**

### CODE REVIEW

**Comment by liu-cong** [comment]
This PR removes the `config/broker` folder as the broker data plane will be dynamically created with brokercell.
@ericlem Let me know if there is anything requried for go mod (I remember you talked about the dummy go file).

cc @nachocano as you are looking at the release yamls

**Comment by nachocano** [comment]
> This PR removes the `config/broker` folder as the broker data plane will be dynamically created with brokercell.
> @ericlem Let me know if there is anything requried for go mod (I remember you talked about the dummy go file).
> 
> cc @nachocano as you are looking at the release yamls

Are you planning on cherry-picking this and other broker stuff to 0.15?

**Comment by ericlem** [comment]
When we merge it into cloudrun-eventing we'll have to remove the entries pointing at the config/broker directories from hack/tools.go (the version in cloudrun-eventing) and the copy_yaml command for it from hack/update-deps.sh (the version in cloudrun-eventing)

**Comment by yolocs** [comment]
It just occurred to me - would it be useful to keep these yamls somewhere for easier testing?

**Comment by liu-cong** [comment]
> It just occurred to me - would it be useful to keep these yamls somewhere for easier testing?

For consistency I would say no since we don't keep yamls for other dynamically created resources. Is there any specific use case you have in mind?

**Comment by yolocs** [comment]
@liu-cong I was thinking the case where I want to create a broker data plane manually. But never mind, once we move to brokercell the existing yamls won't work anyway.

**Comment by liu-cong** [comment]
> I was thinking the case where I want to create a broker data plane manually. But never mind, once we move to brokercell the existing yamls won't work anyway.

Yeah I can see sometimes you want to manually deploy the yamls for troubleshooting for example. We could create a `example yaml` folder to put these yamls. But I am afraid we will forget to keep them up to date... So better just remove them if we won't maintain them.

**Comment by yolocs** [comment]
/hold
It just occurred to me. Will this PR break e2e test? https://github.com/google/knative-gcp/blob/848d632c199e189e6aedd0594c2e392c529d527a/test/lib.sh#L38

**Comment by liu-cong** [comment]
> Will this PR break e2e test?

Indeed it will. And this explains the test failures :)

Also removed the yaml from e2e tests. Let's see if the tests will pass.

**Pull request merged**
