### PR TITLE
unpinning eventing and updating deps

### PR DESCRIPTION
**Pull request by nachocano**
- adding missing test image
- updating deps
- unpinning CE-SDK
- Removing TestBrokerDeadLetterSink as it was removed from eventing. We skipped it anyway and we have a Channel one for that. Although we currently don't support Dead Letter queue in our channel

-->

**Release Note**

```release-note
NONE
```

**Docs**

### CODE REVIEW

**Comment by nachocano** [comment]
fyi @capri-xiyue

**Comment by capri-xiyue** [comment]
/hold 
Wondering whether `TestBrokerDeadLetterSink` needs to be deleted.

**Comment by nachocano** [comment]
> /hold
> Wondering whether `TestBrokerDeadLetterSink` needs to be deleted.

It was removed in eventing. https://github.com/knative/eventing/pull/3300/files#diff-0ba650882e2e28f7a358f1358430bda6

Either way, we have it skipped because our current Channel does not support dead letter queue... We left the channel one skipped at least...

**Comment by nachocano** [comment]
need to run update-codegen

**Comment by capri-xiyue** [comment]
@nachocano  You need to run hack/update-codegen.sh

**Comment by capri-xiyue** [comment]
> /hold
> Wondering whether `TestBrokerDeadLetterSink` needs to be deleted.

/unhold
Synced with @nachocano, the helper method of `TestBrokerDeadLetterSink`in eventing got deleted today. Since we use latest eventing nightly, today it will still pass but tomorrow it will fail.
Therefore, we need to delete ``TestBrokerDeadLetterSink`

**Comment by capri-xiyue** [comment]
I just submitted another PR to update all the deps https://github.com/google/knative-gcp/pull/1257. You don't need to rebase this PR.

**Comment by nachocano** [comment]
closing in favor of https://github.com/google/knative-gcp/pull/1257
Thanks @capri-xiyue

**Pull request closed without merging**
