### PR TITLE
Update event-display image path to support CE 1.0 in GCP broker

### LINKED ISSUE #1275: Update example docs to use cloudevents 1.0
**Problem**
Our [broker examples](https://github.com/google/knative-gcp/tree/master/docs/examples/gcpbroker) currently use CE 0.3.  We should update to 1.0. When I wrote the examples, the `event-display` code didn't support 1.0 version. 

* Check if `event-display` supports 1.0 now. If not, may need to update that first
* Pick a `event-display` image that supports 1.0 and update the docs
* Should also update the Knative docs in https://knative.dev/docs/eventing/getting-started/

**Exit Criteria**
* Examples doc updated using 1.0

### PR DESCRIPTION
**Pull request by danyinggu**
Fixes #1275 

## Proposed Changes

- 🐛 Fixed the event-display image path in the gcp broker example to support CE 1.0
- 🐛 Fixed the gcp broker URL in broker installation guide
- 🐛 Fixed some typos 

**Release Note**

```release-note

```

**Docs**

### CODE REVIEW

**Comment by liu-cong** [comment]
This is great! Thanks @danyinggu

**Comment by danyinggu** [comment]
@googlebot

**Pull request merged**
