### PR TITLE
Auto-update dependencies

### PR DESCRIPTION
**Pull request by mattmoor**
Produced via:
  `./hack/update-deps.sh --upgrade && ./hack/update-codegen.sh`
/assign grantr nachocano
/cc grantr nachocano

### CODE REVIEW

**Comment by grantr** [comment]
See also https://github.com/knative/sample-source/pull/31. Needed to add the `cla: yes` and `cla: no` labels to this repo. Maybe Tide's configuration recently changed to require this label.

**Comment by nachocano** [comment]
> See also [knative/sample-source#31](https://github.com/knative/sample-source/pull/31). Needed to add the `cla: yes` and `cla: no` labels to this repo. Maybe Tide's configuration recently changed to require this label.

Thanks @grantr !!!

**Pull request merged**
