### PR TITLE
Use MTChannelBasedBroker broker class in tests

### PR DESCRIPTION
**Pull request by grantr**
ChannelBasedBroker class is removed from upstream eventing.

## Proposed Changes

- Switch e2e and performance tests to use `MTChannelBasedBroker` broker class

### CODE REVIEW

**Comment by capri-xiyue** [comment]
I reran the  pull-google-knative-gcp-integration-tests. Now the MT Broker with PubSub Channel can be ready. However, MT Broker with PubSub Channe can't receive any events. 
For example, for `TestCloudStorageSourceBrokerWithPubSubChannel`, 
we found logs as below:
` # TYPE source_event_count counter
    source_event_count{event_source="//storage.googleapis.com/buckets/storage-e2e-test-knative-boskos-23",event_type="com.google.cloud.storage.object.delete",name="storage-e2e-test-knative-boskos-23-storage-bnvxahmr",namespace_name="test-cloud-storage-source-broker-with-pub-sub-channel-7bg8s",resource_group="cloudstoragesources.events.cloud.google.com",response_code="400",response_code_class="4xx"} 537
    source_event_count{event_source="//storage.googleapis.com/buckets/storage-e2e-test-knative-boskos-23",event_type="com.google.cloud.storage.object.finalize",name="storage-e2e-test-knative-boskos-23-storage-bnvxahmr",namespace_name="test-cloud-storage-source-broker-with-pub-sub-channel-7bg8s",resource_group="cloudstoragesources.events.cloud.google.com",response_code="400",response_code_class="4xx"} 573`
The root cause of failure is source fails to send cloudevents to MT Broker with PubSub Channel.

**Comment by grantr** [comment]
https://github.com/knative/eventing/issues/3242 makes the MT broker incompatible with the pubsub channel. This PR now skips all tests relying on the MT broker. When https://github.com/knative/eventing/issues/3242 is fixed we can un-skip them.

See also #1176.

**Comment by grantr** [comment]
Tests pass now, so this is ready for review. 

The pin is reverted in this PR. From https://storage.googleapis.com/knative-prow/pr-logs/pull/google_knative-gcp/1173/pull-google-knative-gcp-integration-tests/1267586422596964354/build-log.txt:

`Installing Eventing CRDs from https://storage.googleapis.com/knative-nightly/eventing/latest/eventing.yaml`

**Comment by grantr** [comment]
@chizhg the pubsub channel broker performance tests will fail until https://github.com/knative/eventing/issues/3242 is fixed. This PR doesn't attempt to disable them, so they will continue to fail without further intervention. Since we'll be focusing future performance improvements on the GCP broker, it might sense to remove the channel broker perf tests permanently.

**Comment by chizhg** [comment]
> @chizhg the pubsub channel broker performance tests will fail until [knative/eventing#3242](https://github.com/knative/eventing/issues/3242) is fixed. This PR doesn't attempt to disable them, so they will continue to fail without further intervention. Since we'll be focusing future performance improvements on the GCP broker, it might sense to remove the channel broker perf tests permanently.

I'm fine with removing it. Could you please do it in this PR 😄 ?

**Comment by grantr** [comment]
Removed.

**Comment by chizhg** [comment]
> Removed.

Thank you!
/lgtm

**Pull request merged**
