### PR TITLE
Set Stackdriver as default metrics backend

### PR DESCRIPTION
**Pull request by zargarpur**
And set sampling period to 60 seconds

### CODE REVIEW

**Comment by ian-mi** [comment]
/lgtm
WDYT about disabling custom metrics by default?

**Comment by zargarpur** [comment]
> /lgtm
> WDYT about disabling custom metrics by default?

Is it not disabled by default? I thought you had to explicitly enabled it with `metrics.allow-stackdriver-custom-metrics: "true"`

**Comment by ian-mi** [comment]
Ah you're right, I had missed that we were explicitly enabling them in e2e testing but your other PR should fix that.

**Pull request merged**
