### PR TITLE
[WIP] Impl log slurp

### PR DESCRIPTION
**Pull request by n3wscott**

### CODE REVIEW

**Comment by Harwayne** [comment]
How did this merge without an LGTM?

**Comment by n3wscott** [comment]
I have no idea

**Comment by Harwayne** [comment]
> I have no idea

My _guess_ is that it had identical commits as #162, so once that merged GitHub helpfully said this one did too?

**Comment by adrcunha** [comment]
Tide didn't pass, but since it's not a required task, the bot merged the PR as soon as it was possible. The instructions in knative/test-infra explicitly say to check all test jobs and tide as required checks.

**Pull request merged**
