### PR TITLE
fixed propagate publisher status and fixed the pubsubsecret

### PR DESCRIPTION
**Pull request by capri-xiyue**
Fixes #

## Proposed Changes

- fixed propagate publisher status
- fixed empty pubsubsecret 
-
-

**Release Note**

```release-note

```

### CODE REVIEW

**Comment by nachocano** [comment]
/lgtm
/approve

Thanks for the quick fix!

**Comment by nachocano** [comment]
BTW, have you tried gcloud with storage and scheduler with these fixes and they work?
If so, then we should cherry-pick to 0.12.

**Comment by capri-xiyue** [comment]
> BTW, have you tried gcloud with storage and scheduler with these fixes and they work?
> If so, then we should cherry-pick to 0.12.

The gcloud create trigger works. 
However, when I tried to send event, it doesn't work for all four sources.
I checked the logs of default-broker-ingress, the error logs is as follows:
`{"level":"warn","ts":1581573877.5656204,"logger":"fallback","caller":"http/transport.go:510","msg":"got an error from receiver fn","error":"error sending cloudevent: 500 Internal Server Error"}
{"level":"warn","ts":1581573877.5656753,"logger":"fallback","caller":"http/transport.go:602","msg":"error returned from invokeReceiver","error":"error sending cloudevent: 500 Internal Server Error"}`

I don't think it's related to this PR.  Maybe because I use the latest serving and eventing. Will investigate further tomorrow.

**Comment by nachocano** [comment]
Yeah, that seems something different. We should cherry-pick to 0.12, and
then test with that branch. We can do so tomorrow!

**Comment by capri-xiyue** [comment]
It looks like we also need to cherry-pick this PR  https://github.com/google/knative-gcp/commit/cda1f5c8ed7fd05cd080838223885d0b264567df. My PR is based on it.

**Comment by nachocano** [comment]
OK, that should be fine. And that will help with the debugging as well..

**Pull request merged**
