### PR TITLE
Update 0.8 release branch to master to capture the fixes from last week.

### PR DESCRIPTION
**Pull request by n3wscott**
- channels fixed
- broker fixed
- channel status fixed
- Storage fixed

### CODE REVIEW

**Comment by mattmoor** [comment]
/lgtm
yolo, the commit shas match.

**Comment by n3wscott** [comment]
@googlebot I fixed it.

**Comment by n3wscott** [comment]
the cla fail is for the prow robot account... @adrcunha

**Comment by adrcunha** [comment]
This is the first time I see the Prow robot being an author of a commit. It never signed the CLA because it's not supposed to be an author of a commit in a PR.

**Pull request merged**
