### PR TITLE
Pin knative/pkg and knative/test-infra to release-0.15

### PR DESCRIPTION
**Pull request by Harwayne**
## Proposed Changes

-  Pin `knative/pkg` and `knative/test-infra` to `release-0.15` in anticipation of the 0.15 release.

This was created by:
1. Manually altering `hack/update-deps.sh`.
1. Running `hack/update-deps.sh --upgrade`.

**Release Note**

```release-note
NONE
```

### CODE REVIEW

**Comment by Harwayne** [comment]
@ian-mi is this the correct way to pin dependencies with `go mod`?

**Comment by ian-mi** [comment]
Yes, but you should just change the VERSION var instead.

**Comment by Harwayne** [comment]
> Yes, but you should just change the VERSION var instead.

I thought about that, but didn't because the four places that user `$VERSION` do not all share the same version. Specifically, neither eventing nor serving have the release-0.15 branch yet. S we would need a second variable for them.

This also came up on the equivalent PR to serving, where they decided to hard code it this way: https://github.com/knative/serving/pull/7996#discussion_r427456195.

**Comment by ian-mi** [comment]
In that case this should work. Ideally knative would tag releases with a version tag, the current method essentially pins the dependency to the HEAD commit of the release-0.15 branch.

**Pull request merged**
