### PR TITLE
Update default credential and rename method

### PR DESCRIPTION
**Pull request by grac3gao**
## Proposed Changes

- Update default credential setup. Currently, the default setup will automatically setup the default secret if secret is empty, regardless whether KSA is there or not. If the default auth is Secret, and we specify KSA in sources, it will return error as secret and KSA can't exist as the same time. 
- rename method (DefaultAuthorization -> DefaultGCPAuth)

**Release Note**

```release-note
If either `spec.serviceAccountName` or `spec.secret` is specified, then no additional credential defaulting will be applied to the Source or Channel.
```

### CODE REVIEW

**Comment by grac3gao** [comment]
@Harwayne Thank you for mentioning this! I created a issue to track that #1216

**Comment by capri-xiyue** [comment]
It looks like we encountered this error kind of often 
`{"level":"error","ts":1591303337.6070914,"logger":"fallback","caller":"v1alpha1/pubsub_defaults.go:33","msg":"Failed to get the GCPAuthDefaults","stacktrace":"github.com/google/knative-gcp/pkg/apis/duck/v1alpha1.(*PubSubSpec).SetPubSubDefaults\n\t/home/prow/go/src/github.com/google/knative-gcp/pkg/apis/duck/v1alpha1/pubsub_defaults.go:33\ngithub.com/google/knative-gcp/pkg/apis/intevents/v1alpha1.(*PullSubscriptionSpec).SetDefaults\n\t/home/prow/go/src/github.com/google/knative-gcp/pkg/apis/intevents/v1alpha1/pullsubscription_defaults.go:54\ngithub.com/google/knative-gcp/pkg/apis/intevents/v1alpha1.(*PullSubscription).SetDefaults\n\t/home/prow/go/src/github.com/google/knative-gcp/pkg/apis/intevents/v1alpha1/pullsubscription_defaults.go:38\ngithub.com/google/knative-gcp/pkg/reconciler/testing.NewPullSubscription\n\t/home/prow/go/src/github.com/google/knative-gcp/pkg/reconciler/testing/pullsubscription.go:53\ngithub.com/google/knative-gcp/test/e2e.PullSubscriptionWithTargetTestImpl\n\t/home/prow/go/src/github.com/google/knative-gcp/test/e2e/test_pullsubscription.go:84\ngithub.com/google/knative-gcp/test/e2e.TestPullSubscriptionWithTarget\n\t/home/prow/go/src/github.com/google/knative-gcp/test/e2e/e2e_test.go:174\ntesting.tRunner\n\t/root/.gvm/gos/go1.14.2/src/testing/testing.go:991"}` which cause the flakiness of e2e tests

**Comment by grac3gao** [comment]
@capri-xiyue If you are referring to the flakiness only for this PR, `Failed to get the GCPAuthDefaults` is not the root cause for it. We added a new ConfigMap for GCP Auth to set credential in webhook. This configMap is not installed when running wi e2e test. It will not affect the proper credential setup in the wi e2e test, as we specified a GSA, and are not relying the default webhook. Other PRs also shows `Failed to get the GCPAuthDefaults`, but it doesn't affect the test result.  

However, it is true that the test is more flaky, I'll investigate it....

**Comment by Harwayne** [comment]
> It looks like we encountered this error kind of often
> `{"level":"error","ts":1591303337.6070914,"logger":"fallback","caller":"v1alpha1/pubsub_defaults.go:33","msg":"Failed to get the GCPAuthDefaults","stacktrace":"github.com/google/knative-gcp/pkg/apis/duck/v1alpha1.(*PubSubSpec).SetPubSubDefaults\n\t/home/prow/go/src/github.com/google/knative-gcp/pkg/apis/duck/v1alpha1/pubsub_defaults.go:33\ngithub.com/google/knative-gcp/pkg/apis/intevents/v1alpha1.(*PullSubscriptionSpec).SetDefaults\n\t/home/prow/go/src/github.com/google/knative-gcp/pkg/apis/intevents/v1alpha1/pullsubscription_defaults.go:54\ngithub.com/google/knative-gcp/pkg/apis/intevents/v1alpha1.(*PullSubscription).SetDefaults\n\t/home/prow/go/src/github.com/google/knative-gcp/pkg/apis/intevents/v1alpha1/pullsubscription_defaults.go:38\ngithub.com/google/knative-gcp/pkg/reconciler/testing.NewPullSubscription\n\t/home/prow/go/src/github.com/google/knative-gcp/pkg/reconciler/testing/pullsubscription.go:53\ngithub.com/google/knative-gcp/test/e2e.PullSubscriptionWithTargetTestImpl\n\t/home/prow/go/src/github.com/google/knative-gcp/test/e2e/test_pullsubscription.go:84\ngithub.com/google/knative-gcp/test/e2e.TestPullSubscriptionWithTarget\n\t/home/prow/go/src/github.com/google/knative-gcp/test/e2e/e2e_test.go:174\ntesting.tRunner\n\t/root/.gvm/gos/go1.14.2/src/testing/testing.go:991"}` which cause the flakiness of e2e tests

This is related to #1183, not this PR. #1220 should remove the error message from the test logs.

**Comment by grac3gao** [comment]
@Harwayne topic default changed, with some UT updated.

**Pull request merged**
