### PR TITLE
moved channel storage version to v1beta1

### PR DESCRIPTION
**Pull request by capri-xiyue**
Fixes #

## Proposed Changes

- - 🧽 moved channel storage version to v1beta1

**Release Note**
moved channel storage version to v1beta1

### CODE REVIEW

**Comment by capri-xiyue** [comment]
I tested in local.
Somehow after we channel storage version to v1beta1, subscription can't be ready even though channel are ready.
How to reproduce that in local:
https://github.com/knative/eventing/issues/3318

**Comment by capri-xiyue** [comment]
This is not a high priority issue, I will try to figure it out later

**Comment by Harwayne** [comment]
/hold

Holding due to:

> This is not a high priority issue, I will try to figure it out later

So that it is easily distinguished in the list of PRs.

**Comment by danyinggu** [comment]
The subscription not ready issue should be resolved by #1312

**Pull request merged**
