### PR TITLE
[Automated] Format Go code

### PR DESCRIPTION
**Pull request by mattmoor**
Produced via:
```shell
export FILES=( $(find -path './vendor' -prune -o -path './third_party' -prune -o -name '*.pb.go' -prune -o -type f -name '*.go' -print) )
goimports -w "${FILES[@]}"
gofmt -s -w  "${FILES[@]}"
```
/cc nachocano grantr ian-mi
/assign nachocano grantr ian-mi

### CODE REVIEW

**Comment by Harwayne** [comment]
The issue seems to be an incorrect import order in `wire_gen.go`:

```
diff -Naupr --no-dereference /home/prow/go/src/github.com/google/knative-gcp/pkg/broker/handler/wire_gen.go /tmp/tmpdiffroot.qtJQvW/pkg/broker/handler/wire_gen.go
--- /home/prow/go/src/github.com/google/knative-gcp/pkg/broker/handler/wire_gen.go	2020-09-25 17:10:44.696930122 +0000
+++ /tmp/tmpdiffroot.qtJQvW/pkg/broker/handler/wire_gen.go	2020-09-25 16:58:02.560306703 +0000
@@ -6,8 +6,9 @@
 package handler
 
 import (
-	"cloud.google.com/go/pubsub"
 	"context"
+
+	"cloud.google.com/go/pubsub"
 	"github.com/google/knative-gcp/pkg/broker/config"
 	"github.com/google/knative-gcp/pkg/metrics"
 )
/home/prow/go/src/github.com/google/knative-gcp is out of date. Please run hack/update-codegen.sh
```

@ian-mi didn't we have to explicitly ignore these files in the past?

**Comment by mattmoor** [comment]
I may have dropped something porting thing to actions.  Perhaps I need to add `_wire.go` to the exclude list or something?

**Pull request closed without merging**
